// Package clidocs generates the command reference (docs/commands) and the
// man pages from the cobra command tree, so they cannot drift from --help.
// It is used by `make docs`, `make man`, the goreleaser hook and tests; the
// skenv binary does not link it.
package clidocs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/qunaxis/skenv/internal/cli"
	"github.com/qunaxis/skenv/internal/cliexample"
)

const header = "<!-- Generated by `make docs` from the skenv command definitions; do not edit. -->\n\n"

// Generate writes one Markdown file per command into dir and removes
// Markdown files of commands that no longer exist. The output of the
// examples comes from the golden files under examplesRoot (the committed
// docs/commands: examples/<command>/<n>.txt).
func Generate(dir, examplesRoot string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	old, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	root := cli.Command()
	formatHelp(root)
	prepend := func(string) string { return header }
	link := func(name string) string { return name }
	if err := doc.GenMarkdownTreeCustom(root, dir, prepend, link); err != nil {
		return err
	}
	if err := addOutput(root, dir, examplesRoot); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "README.md"), []byte(index(root)), 0o644)
}

// index lists every command with its one-line summary.
func index(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString(header + "# Command reference\n\n")
	b.WriteString("Generated from `skenv --help`. Start with [skenv](skenv.md).\n\n")
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if !c.IsAvailableCommand() && c != root {
			return
		}
		name := strings.ReplaceAll(c.CommandPath(), " ", "_") + ".md"
		b.WriteString("- [" + c.CommandPath() + "](" + name + "): " + c.Short + "\n")
		for _, s := range c.Commands() {
			walk(s)
		}
	}
	walk(root)
	return b.String()
}

// formatHelp code-formats the Short and Long text of every command in the
// tree (a copy built for the reference, not the one `skenv` runs).
func formatHelp(c *cobra.Command) {
	c.Short = codeFormat(c.Short)
	c.Long = codeFormat(c.Long)
	for _, s := range c.Commands() {
		formatHelp(s)
	}
}

// addOutput replaces cobra's Examples section of every page with one that
// shows the recorded output under each example. The output is embedded as
// it is: codeFormat only sees the comments of the examples.
func addOutput(c *cobra.Command, dir, examplesRoot string) error {
	if c.Example != "" {
		page := filepath.Join(dir, strings.ReplaceAll(c.CommandPath(), " ", "_")+".md")
		b, err := os.ReadFile(page)
		if err != nil {
			return err
		}
		section, err := examples(c.CommandPath(), c.Example, func(n int) (cliexample.Output, bool, error) {
			return cliexample.Read(filepath.Join(examplesRoot, cliexample.File(c.CommandPath(), n)))
		})
		if err != nil {
			return err
		}
		cobraSection := "### Examples\n\n```\n" + c.Example + "\n```\n\n"
		if !strings.Contains(string(b), cobraSection) {
			return fmt.Errorf("%s: no Examples section in cobra's format", page)
		}
		out := strings.Replace(string(b), cobraSection, section, 1)
		if err := os.WriteFile(page, []byte(out), 0o644); err != nil {
			return err
		}
	}
	for _, s := range c.Commands() {
		if s.IsAvailableCommand() && !s.IsAdditionalHelpTopicCommand() {
			if err := addOutput(s, dir, examplesRoot); err != nil {
				return err
			}
		}
	}
	return nil
}

// examples renders the Examples section: each example as a console block
// with its output and, when it is not 0, the exit code. Examples without a
// comment and without output share one block.
func examples(path, field string, output func(n int) (cliexample.Output, bool, error)) (string, error) {
	var b strings.Builder
	b.WriteString("### Examples\n\n")
	open := false // a block of examples without output is open
	for i, ex := range cliexample.Parse(field) {
		out, ok, err := output(i + 1)
		if err != nil {
			return "", err
		}
		if open && (ex.Comment != "" || ok) {
			b.WriteString("```\n\n")
			open = false
		}
		if ex.Comment != "" {
			b.WriteString(codeFormat(ex.Comment) + ":\n\n")
		}
		if !open {
			b.WriteString("```console\n")
		}
		b.WriteString("$ " + ex.Line + "\n")
		if !ok {
			open = true
			continue
		}
		if strings.Contains(out.Text, "```") {
			return "", fmt.Errorf("%s: output of example %d contains a code fence", path, i+1)
		}
		b.WriteString(out.Text)
		if out.Text != "" && !strings.HasSuffix(out.Text, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("```\n\n")
		if out.Code != 0 {
			fmt.Fprintf(&b, "Exit code %d.\n\n", out.Code)
		}
	}
	if open {
		b.WriteString("```\n\n")
	}
	return b.String(), nil
}
