// Package clidocs generates the command reference (docs/commands) and the
// man pages from the cobra command tree, so they cannot drift from --help.
// It is used by `make docs`, `make man`, the goreleaser hook and tests; the
// skenv binary does not link it.
package clidocs

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/qunaxis/skenv/internal/cli"
)

const header = "<!-- Generated by `make docs` from the skenv command definitions; do not edit. -->\n\n"

// Generate writes one Markdown file per command into dir and removes
// Markdown files of commands that no longer exist.
func Generate(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	old, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	root := cli.Command()
	formatHelp(root)
	prepend := func(string) string { return header }
	link := func(name string) string { return name }
	if err := doc.GenMarkdownTreeCustom(root, dir, prepend, link); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "README.md"), []byte(index(root)), 0o644)
}

// index lists every command with its one-line summary.
func index(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString(header + "# Command reference\n\n")
	b.WriteString("Generated from `skenv --help`. Start with [skenv](skenv.md).\n\n")
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if !c.IsAvailableCommand() && c != root {
			return
		}
		name := strings.ReplaceAll(c.CommandPath(), " ", "_") + ".md"
		b.WriteString("- [" + c.CommandPath() + "](" + name + "): " + c.Short + "\n")
		for _, s := range c.Commands() {
			walk(s)
		}
	}
	walk(root)
	return b.String()
}

// formatHelp code-formats the Short and Long text of every command in the
// tree (a copy built for the reference, not the one `skenv` runs).
func formatHelp(c *cobra.Command) {
	c.Short = codeFormat(c.Short)
	c.Long = codeFormat(c.Long)
	for _, s := range c.Commands() {
		formatHelp(s)
	}
}
