#!/usr/bin/env bash
# Cut a release from Conventional Commits (PRD V3-V8):
#   version (git-cliff) -> CHANGELOG.md -> "chore(release): vX.Y.Z"
#   -> annotated tag -> push -> goreleaser with git-cliff release notes.
# Safe to rerun until the tag exists: a pending release commit is reused.
# Needs GITHUB_TOKEN in the environment, e.g.
#   GITHUB_TOKEN="$(gh auth token)" make release
set -euo pipefail

die() { echo "release: $*" >&2; exit 1; }

cd "$(git rev-parse --show-toplevel)"
[[ -n ${GITHUB_TOKEN:-} ]] || die 'GITHUB_TOKEN is not set (GITHUB_TOKEN="$(gh auth token)" make release)'
for tool in git-cliff goreleaser go; do
	command -v "$tool" >/dev/null || die "$tool is not installed"
done
[[ $(git rev-parse --abbrev-ref HEAD) == main ]] || die "releases are cut from main"
[[ -z $(git status --porcelain) ]] || die "working tree is not clean"
git fetch --quiet --tags origin main
git merge-base --is-ancestor origin/main HEAD || die "main is behind origin/main; pull first"

version=""
head_tag=$(git tag --points-at HEAD --list 'v[0-9]*.[0-9]*.[0-9]*' | head -n1)
subject=$(git log -1 --format=%s)
if [[ -n $head_tag ]]; then
	version=$head_tag
	echo "release: HEAD is already tagged $version; publishing it"
elif [[ $subject =~ ^chore\(release\):\ (v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
	version=${BASH_REMATCH[1]}
	echo "release: reusing pending release commit for $version"
else
	last=$(git describe --tags --abbrev=0 --match 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null || true)
	version=$(git cliff --bumped-version 2>/dev/null)
	[[ $version =~ ^v0\.[0-9]+\.[0-9]+$ ]] || die "unexpected version '$version' (only 0.x releases before the owner decides on 1.0.0)"
	if [[ -n $last && $version == "$last" ]]; then
		echo "release: no feat/fix/perf/breaking commits since $last; nothing to release"
		exit 0
	fi
	echo "release: ${last:-(no tag)} -> $version"
	go vet ./...
	go test ./...
	# Keep the tree clean if anything below fails, so a rerun starts over.
	restore_changelog() {
		git reset -q -- CHANGELOG.md 2>/dev/null || true
		git checkout -q HEAD -- CHANGELOG.md 2>/dev/null || rm -f CHANGELOG.md
	}
	trap restore_changelog ERR
	git cliff --tag "$version" -o CHANGELOG.md
	git add CHANGELOG.md
	body="Generated by make release from the Conventional Commits since ${last:-the first commit}."
	if [[ -n ${RELEASE_COMMIT_TRAILER:-} ]]; then
		git commit --quiet -m "chore(release): $version" -m "$body" -m "$RELEASE_COMMIT_TRAILER"
	else
		git commit --quiet -m "chore(release): $version" -m "$body"
	fi
	trap - ERR
fi

if [[ -z $head_tag ]]; then
	git tag -a "$version" -m "skenv $version"
fi
git push --quiet --atomic origin HEAD:main "refs/tags/$version"

notes=$(mktemp)
trap 'rm -f "$notes"' EXIT
git cliff --latest --strip header -o "$notes"
# An empty file would make goreleaser fall back to its own changelog.
[[ -s $notes ]] || die "git-cliff produced empty release notes for $version"
goreleaser release --clean --release-notes "$notes"
echo "release: published $version"
